services:
  rabbitmq:
    container_name: rabbitmq
    env_file:
      - core-service/.env
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    env_file:
      - core-service/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    env_file:
      - core-service/.env
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false

  app:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    container_name: core
    profiles:
      - prod
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - ./core-service/.env.dev
      - ./core-service/.env

volumes:
  rabbitmq_data:
  mongodb_data: